apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ./namespace.yaml
  - ./prometheus
  - ./grafana
  - ./alertmanager
  - ./node-exporter.yaml
  - ./pushgateway.yaml
  - ./snmp-exporter.yaml
