{
 "title": "NodeExporterFull",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "QuickCPU/Mem/Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPUBusy",
   "type": "gauge",
   "description": "BusystateofallCPUcorestogether",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode!=\"idle\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))))*100"
    }
   ]
  },
  {
   "title": "SysLoad(5mavg)",
   "type": "gauge",
   "description": "BusystateofallCPUcorestogether(5minaverage)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"})/count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"})by(cpu))*100"
    }
   ]
  },
  {
   "title": "SysLoad(15mavg)",
   "type": "gauge",
   "description": "BusystateofallCPUcorestogether(15minaverage)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"})/count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"})by(cpu))*100"
    }
   ]
  },
  {
   "title": "RAMUsed",
   "type": "gauge",
   "description": "NonavailableRAMmemory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"}*100)/node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAPUsed",
   "type": "gauge",
   "description": "UsedSwap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}-node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})/(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}))*100"
    }
   ]
  },
  {
   "title": "RootFSUsed",
   "type": "gauge",
   "description": "UsedRootFS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}*100)/node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPUCores",
   "type": "stat",
   "description": "TotalnumberofCPUcores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"})by(cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Systemuptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"}-node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFSTotal",
   "type": "stat",
   "description": "TotalRootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAMTotal",
   "type": "stat",
   "description": "TotalRAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAPTotal",
   "type": "stat",
   "description": "TotalSWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "BasicCPU/Mem/Net/Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPUBasic",
   "type": "timeseries",
   "description": "BasicCPUinfo",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"system\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "BusySystem"
    },
    {
     "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"user\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "BusyUser"
    },
    {
     "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"iowait\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "BusyIowait"
    },
    {
     "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=~\".*irq\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "BusyIRQs"
    },
    {
     "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "BusyOther"
    },
    {
     "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"idle\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "MemoryBasic",
   "type": "timeseries",
   "description": "Basicmemoryusage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAMTotal"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}-node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}-(node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}+node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}+node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAMUsed"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}+node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}+node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAMCache+Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAMFree"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}-node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAPUsed"
    }
   ]
  },
  {
   "title": "NetworkTrafficBasic",
   "type": "timeseries",
   "description": "Basicnetworkinfoperinterface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans{{device}}"
    }
   ]
  },
  {
   "title": "DiskSpaceUsedBasic",
   "type": "timeseries",
   "description": "Diskspaceusedofallfilesystemsmounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}*100)/node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU/Memory/Net/Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"system\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "System-Processesexecutinginkernelmode"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"user\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "User-Normalprocessesexecutinginusermode"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"nice\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Nice-Nicedprocessesexecutinginusermode"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"iowait\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Iowait-WaitingforI/Otocomplete"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"irq\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Irq-Servicinginterrupts"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"softirq\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Softirq-Servicingsoftirqs"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"steal\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Steal-Timespentinotheroperatingsystemswhenrunninginavirtualizedenvironment"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"idle\"}[$__rate_interval]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "Idle-Waitingforsomethingtohappen"
      }
     ]
    },
    {
     "title": "MemoryStack",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}-node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}-node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}-node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}-node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"}-node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}-node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Apps-Memoryusedbyuser-spaceapplications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "PageTables-Memoryusedtomapbetweenvirtualandphysicalmemoryaddresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SwapCache-Memorythatkeepstrackofpagesthathavebeenfetchedfromswapbutnotyetbeenmodified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Slab-Memoryusedbythekerneltocachedatastructuresforitsownuse(cacheslikeinode,dentry,etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Cache-Parkedfiledata(filecontent)cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Buffers-Blockdevice(e.g.harddisk)cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Unused-Freememoryunassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}-node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Swap-Swapspaceused"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HardwareCorrupted-AmountofRAMthatthekernelidentifiedascorrupted/notworking"
      }
     ]
    },
    {
     "title": "NetworkTraffic",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}}-Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}}-Transmit"
      }
     ]
    },
    {
     "title": "DiskSpaceUsed",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}-node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "DiskIOps",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Readscompleted"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Writescompleted"
      }
     ]
    },
    {
     "title": "I/OUsageRead/Write",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Successfullyreadbytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Successfullywrittenbytes"
      }
     ]
    },
    {
     "title": "I/OUtilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "CPUspentsecondsinguests(VMs)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sumby(instance)(irate(node_cpu_guest_seconds_total{instance=\"$node\",job=\"$job\",mode=\"user\"}[1m]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[1m])))",
       "legendFormat": "Guest-TimespentrunningavirtualCPUforaguestoperatingsystem"
      },
      {
       "expr": "sumby(instance)(irate(node_cpu_guest_seconds_total{instance=\"$node\",job=\"$job\",mode=\"nice\"}[1m]))/on(instance)group_leftsumby(instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[1m])))",
       "legendFormat": "GuestNice-Timespentrunninganicedguest(virtualCPUforguestoperatingsystem)"
      }
     ]
    }
   ]
  },
  {
   "title": "MemoryMeminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MemoryActive/Inactive",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Inactive-Memorywhichhasbeenlessrecentlyused.Itismoreeligibletobereclaimedforotherpurposes"
      },
      {
       "expr": "node_memory_Active_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active-Memorythathasbeenusedmorerecentlyandusuallynotreclaimedunlessabsolutelynecessary"
      }
     ]
    },
    {
     "title": "MemoryCommitted",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Committed_AS-Amountofmemorypresentlyallocatedonthesystem"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "CommitLimit-Amountofmemorycurrentlyavailabletobeallocatedonthesystem"
      }
     ]
    },
    {
     "title": "MemoryActive/InactiveDetail",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Inactive_file-File-backedmemoryoninactiveLRUlist"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Inactive_anon-AnonymousandswapcacheoninactiveLRUlist,includingtmpfs(shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active_file-File-backedmemoryonactiveLRUlist"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active_anon-Anonymousandswapcacheonactiveleast-recently-used(LRU)list,includingtmpfs"
      }
     ]
    },
    {
     "title": "MemoryWritebackandDirty",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Writeback-Memorywhichisactivelybeingwrittenbacktodisk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "WritebackTmp-MemoryusedbyFUSEfortemporarywritebackbuffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Dirty-Memorywhichiswaitingtogetwrittenbacktothedisk"
      }
     ]
    },
    {
     "title": "MemorySharedandMapped",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Mapped-Usedmemoryinmappedpagesfileswhichhavebeenmapped,suchaslibraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Shmem-Usedsharedmemory(sharedbetweenseveralprocesses,thusincludingRAMdisks)"
      },
      {
       "expr": "node_memory_ShmemHugePages_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "ShmemHugePages-Memoryusedbysharedmemory(shmem)andtmpfsallocatedwithhugepages"
      },
      {
       "expr": "node_memory_ShmemPmdMapped_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "ShmemPmdMapped-Amountofshared(shmem/tmpfs)memorybackedbyhugepages"
      }
     ]
    },
    {
     "title": "MemorySlab",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SUnreclaim-PartofSlab,thatcannotbereclaimedonmemorypressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SReclaimable-PartofSlab,thatmightbereclaimed,suchascaches"
      }
     ]
    },
    {
     "title": "MemoryVmalloc",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "VmallocChunk-Largestcontiguousblockofvmallocareawhichisfree"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "VmallocTotal-Totalsizeofvmallocmemoryarea"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "VmallocUsed-Amountofvmallocareawhichisused"
      }
     ]
    },
    {
     "title": "MemoryBounce",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Bounce-Memoryusedforblockdevicebouncebuffers"
      }
     ]
    },
    {
     "title": "MemoryAnonymous",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "AnonHugePages-Memoryinanonymoushugepages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "AnonPages-Memoryinuserpagesnotbackedbyfiles"
      }
     ]
    },
    {
     "title": "MemoryKernel/CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "KernelStack-Kernelmemorystack.Thisisnotreclaimable"
      },
      {
       "expr": "node_memory_Percpu_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "PerCPU-PerCPUmemoryallocateddynamicallybyloadablemodules"
      }
     ]
    },
    {
     "title": "MemoryHugePagesCounter",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages_Free-Hugepagesinthepoolthatarenotyetallocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages_Rsvd-Hugepagesforwhichacommitmenttoallocatefromthepoolhasbeenmade,butnoallocationhasyetbeenmade"
      },
      {
       "expr": "node_memory_HugePages_Surp{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages_Surp-Hugepagesinthepoolabovethevaluein/proc/sys/vm/nr_hugepages"
      }
     ]
    },
    {
     "title": "MemoryHugePagesSize",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages-Totalsizeofthepoolofhugepages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Hugepagesize-HugePagesize"
      }
     ]
    },
    {
     "title": "MemoryDirectMap",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_DirectMap1G_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "DirectMap1G-Amountofpagesmappedasthissize"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "DirectMap2M-Amountofpagesmappedasthissize"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "DirectMap4K-Amountofpagesmappedasthissize"
      }
     ]
    },
    {
     "title": "MemoryUnevictableandMLocked",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Unevictable-Amountofunevictablememorythatcan'tbeswappedoutforavarietyofreasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "MLocked-Sizeofpageslockedtomemoryusingthemlock()systemcall"
      }
     ]
    },
    {
     "title": "MemoryNFS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NFSUnstable-MemoryinNFSpagessenttotheserver,butnotyetcommittedtothestorage"
      }
     ]
    }
   ]
  },
  {
   "title": "MemoryVmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MemoryPagesIn/Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pagesin-Pageinoperations"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pagesout-Pageoutoperations"
      }
     ]
    },
    {
     "title": "MemoryPagesSwapIn/Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pswpin-Pagesswappedin"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pswpout-Pagesswappedout"
      }
     ]
    },
    {
     "title": "MemoryPageFaults",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgfault-Pagemajorandminorfaultoperations"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgmajfault-Majorpagefaultoperations"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])-irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgminfault-Minorpagefaultoperations"
      }
     ]
    },
    {
     "title": "OOMKiller",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_oom_kill{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "oomkillerinvocations"
      }
     ]
    }
   ]
  },
  {
   "title": "SystemTimesync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TimeSynchronizedDrift",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Estimatederrorinseconds"
      },
      {
       "expr": "node_timex_offset_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Timeoffsetinbetweenlocalsystemandreferenceclock"
      },
      {
       "expr": "node_timex_maxerror_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maximumerrorinseconds"
      }
     ]
    },
    {
     "title": "TimePLLAdjust",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_timex_loop_time_constant{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Phase-lockedlooptimeadjust"
      }
     ]
    },
    {
     "title": "TimeSynchronizedStatus",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_timex_sync_status{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Isclocksynchronizedtoareliableserver(1=yes,0=no)"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Localclockfrequencyadjustment"
      }
     ]
    },
    {
     "title": "TimeMisc",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_tick_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Secondsbetweenclockticks"
      },
      {
       "expr": "node_timex_tai_offset_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "InternationalAtomicTime(TAI)offset"
      }
     ]
    }
   ]
  },
  {
   "title": "SystemProcesses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ProcessesStatus",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "ProcessesblockedwaitingforI/Otocomplete"
      },
      {
       "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Processesinrunnablestate"
      }
     ]
    },
    {
     "title": "ProcessesState",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_state{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "ProcessesForks",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_forks_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Processesforkssecond"
      }
     ]
    },
    {
     "title": "ProcessesMemory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Processesvirtualmemorysizeinbytes"
      },
      {
       "expr": "process_resident_memory_max_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maximumamountofvirtualmemoryavailableinbytes"
      },
      {
       "expr": "irate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Processesvirtualmemorysizeinbytes"
      },
      {
       "expr": "irate(process_virtual_memory_max_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Maximumamountofvirtualmemoryavailableinbytes"
      }
     ]
    },
    {
     "title": "PIDsNumberandLimit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_pids{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NumberofPIDs"
      },
      {
       "expr": "node_processes_max_processes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "PIDslimit"
      }
     ]
    },
    {
     "title": "ProcessschedulestatsRunning/Waiting",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_schedstat_running_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU{{cpu}}-secondsspentrunningaprocess"
      },
      {
       "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU{{cpu}}-secondsspentbyprocessingwaitingforthisCPU"
      }
     ]
    },
    {
     "title": "ThreadsNumberandLimit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_threads{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Allocatedthreads"
      },
      {
       "expr": "node_processes_max_threads{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Threadslimit"
      }
     ]
    }
   ]
  },
  {
   "title": "SystemMisc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ContextSwitches/Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Contextswitches"
      },
      {
       "expr": "irate(node_intr_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "SystemLoad",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load1m"
      },
      {
       "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load5m"
      },
      {
       "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load15m"
      }
     ]
    },
    {
     "title": "InterruptsDetail",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_interrupts_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{type}}-{{info}}"
      }
     ]
    },
    {
     "title": "Scheduletimeslicesexecutedbyeachcpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_schedstat_timeslices_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU{{cpu}}"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_entropy_available_bits{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Entropyavailabletorandomnumbergenerators"
      }
     ]
    },
    {
     "title": "CPUtimespentinuserandsystemcontexts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Timespent"
      }
     ]
    },
    {
     "title": "FileDescriptors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maximumopenfiledescriptors"
      },
      {
       "expr": "process_open_fds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Openfiledescriptors"
      }
     ]
    }
   ]
  },
  {
   "title": "HardwareMisc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hardwaretemperaturemonitor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{chip}}{{sensor}}temp"
      },
      {
       "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{chip}}{{sensor}}Critical"
      }
     ]
    },
    {
     "title": "Throttlecoolingdevice",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_cooling_device_cur_state{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Current{{name}}in{{type}}"
      },
      {
       "expr": "node_cooling_device_max_state{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max{{name}}in{{type}}"
      }
     ]
    },
    {
     "title": "Powersupply",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_power_supply_online{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{power_supply}}online"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SystemdSockets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_systemd_socket_accepted_connections_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{name}}Connections"
      }
     ]
    },
    {
     "title": "SystemdUnitsState",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"activating\"}",
       "legendFormat": "Activating"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"active\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"deactivating\"}",
       "legendFormat": "Deactivating"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"failed\"}",
       "legendFormat": "Failed"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"inactive\"}",
       "legendFormat": "Inactive"
      }
     ]
    }
   ]
  },
  {
   "title": "StorageDisk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DiskIOpsCompleted",
     "type": "timeseries",
     "description": "Thenumber(aftermerges)ofI/Orequestscompletedpersecondforthedevice",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Readscompleted"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Writescompleted"
      }
     ]
    },
    {
     "title": "DiskR/WData",
     "type": "timeseries",
     "description": "Thenumberofbytesreadfromorwrittentothedevicepersecond",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Readbytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Writtenbytes"
      }
     ]
    },
    {
     "title": "DiskAverageWaitTime",
     "type": "timeseries",
     "description": "Theaveragetimeforrequestsissuedtothedevicetobeserved.Thisincludesthetimespentbytherequestsinqueueandthetimespentservicingthem.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])/irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Readwaittimeavg"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])/irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Writewaittimeavg"
      }
     ]
    },
    {
     "title": "AverageQueueSize",
     "type": "timeseries",
     "description": "Theaveragequeuelengthoftherequeststhatwereissuedtothedevice",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "DiskR/WMerged",
     "type": "timeseries",
     "description": "Thenumberofreadandwriterequestsmergedpersecondthatwerequeuedtothedevice",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Readmerged"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Writemerged"
      }
     ]
    },
    {
     "title": "TimeSpentDoingI/Os",
     "type": "timeseries",
     "description": "PercentageofelapsedtimeduringwhichI/Orequestswereissuedtothedevice(bandwidthutilizationforthedevice).Devicesaturationoccurswhenthisvalueiscloseto100%fordevicesservingrequestsserially.Butfordevicesservingrequestsinparallel,suchasRAIDarraysandmodernSSDs,thisnumberdoesnotreflecttheirperformancelimits.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-IO"
      },
      {
       "expr": "irate(node_disk_discard_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-discard"
      }
     ]
    },
    {
     "title": "InstantaneousQueueSize",
     "type": "timeseries",
     "description": "Thenumberofoutstandingrequestsattheinstantthesamplewastaken.Incrementedasrequestsaregiventoappropriatestructrequest_queueanddecrementedastheyfinish.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}-IOnow"
      }
     ]
    },
    {
     "title": "DiskIOpsDiscardscompleted/merged",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_discards_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Discardscompleted"
      },
      {
       "expr": "irate(node_disk_discards_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Discardsmerged"
      }
     ]
    }
   ]
  },
  {
   "title": "StorageFilesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filesystemspaceavailable",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}-Available"
      }
     ]
    },
    {
     "title": "FileNodesFree",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}-Freefilenodes"
      }
     ]
    },
    {
     "title": "FileDescriptor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maxopenfiles"
      },
      {
       "expr": "node_filefd_allocated{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Openfiles"
      }
     ]
    },
    {
     "title": "FileNodesSize",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_files{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}-Filenodestotal"
      }
     ]
    },
    {
     "title": "FilesysteminReadOnly/Error",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}-ReadOnly"
      },
      {
       "expr": "node_filesystem_device_error{instance=\"$node\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs'}",
       "legendFormat": "{{mountpoint}}-Deviceerror"
      }
     ]
    }
   ]
  },
  {
   "title": "NetworkTraffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NetworkTrafficbyPackets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Transmit"
      }
     ]
    },
    {
     "title": "NetworkTrafficErrors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receiveerrors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Rransmiterrors"
      }
     ]
    },
    {
     "title": "NetworkTrafficDrop",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receivedrop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Transmitdrop"
      }
     ]
    },
    {
     "title": "NetworkTrafficCompressed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_compressed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receivecompressed"
      },
      {
       "expr": "irate(node_network_transmit_compressed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Transmitcompressed"
      }
     ]
    },
    {
     "title": "NetworkTrafficMulticast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_multicast_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receivemulticast"
      }
     ]
    },
    {
     "title": "NetworkTrafficFifo",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_fifo_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receivefifo"
      },
      {
       "expr": "irate(node_network_transmit_fifo_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Transmitfifo"
      }
     ]
    },
    {
     "title": "NetworkTrafficFrame",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_frame_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Receiveframe"
      }
     ]
    },
    {
     "title": "NetworkTrafficCarrier",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_carrier_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Statistictransmit_carrier"
      }
     ]
    },
    {
     "title": "NetworkTrafficColls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_colls_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}-Transmitcolls"
      }
     ]
    },
    {
     "title": "NFContrack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NFconntrackentries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NFconntracklimit"
      }
     ]
    },
    {
     "title": "ARPEntries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}-ARPentries"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_network_mtu_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}-Bytes"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_network_speed_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}-Speed"
      }
     ]
    },
    {
     "title": "QueueLength",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}-Interfacetransmitqueuelength"
      }
     ]
    },
    {
     "title": "SoftnetPackets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_softnet_processed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU{{cpu}}-Processed"
      },
      {
       "expr": "irate(node_softnet_dropped_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU{{cpu}}-Dropped"
      }
     ]
    },
    {
     "title": "SoftnetOutofQuota",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_softnet_times_squeezed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU{{cpu}}-Squeezed"
      }
     ]
    },
    {
     "title": "NetworkOperationalStatus",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_network_up{operstate=\"up\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{interface}}-OperationalstateUP"
      },
      {
       "expr": "node_network_carrier{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}-Physicallinkstate"
      }
     ]
    }
   ]
  },
  {
   "title": "NetworkSockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SockstatTCP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "TCP_alloc-Allocatedsockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "TCP_inuse-Tcpsocketscurrentlyinuse"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "TCP_orphan-Orphansockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "TCP_tw-Socketswaitingclose"
      }
     ]
    },
    {
     "title": "SockstatUDP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "UDPLITE_inuse-Udplitesocketscurrentlyinuse"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "UDP_inuse-Udpsocketscurrentlyinuse"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "UDP_mem-Usedmemoryforudp"
      }
     ]
    },
    {
     "title": "SockstatFRAG/RAW",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "FRAG_inuse-Fragsocketscurrentlyinuse"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAW_inuse-Rawsocketscurrentlyinuse"
      }
     ]
    },
    {
     "title": "SockstatMemorySize",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "mem_bytes-TCPsocketsinthatstate"
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "mem_bytes-UDPsocketsinthatstate"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "FRAG_memory-Usedmemoryforfrag"
      }
     ]
    },
    {
     "title": "SockstatUsed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Sockets_used-Socketscurrentlyinuse"
      }
     ]
    }
   ]
  },
  {
   "title": "NetworkNetstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NetstatIPIn/OutOctets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InOctets-Receivedoctets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutOctets-Sentoctets"
      }
     ]
    },
    {
     "title": "NetstatIPForwarding",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_Forwarding{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Forwarding-IPforwarding"
      }
     ]
    },
    {
     "title": "ICMPIn/Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InMsgs-Messageswhichtheentityreceived.NotethatthiscounterincludesallthosecountedbyicmpInErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutMsgs-Messageswhichthisentityattemptedtosend.NotethatthiscounterincludesallthosecountedbyicmpOutErrors"
      }
     ]
    },
    {
     "title": "ICMPErrors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrors-MessageswhichtheentityreceivedbutdeterminedashavingICMP-specificerrors(badICMPchecksums,badlength,etc.)"
      }
     ]
    },
    {
     "title": "UDPIn/Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InDatagrams-Datagramsreceived"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutDatagrams-Datagramssent"
      }
     ]
    },
    {
     "title": "UDPErrors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrors-UDPDatagramsthatcouldnotbedeliveredtoanapplication"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "NoPorts-UDPDatagramsreceivedonaportwithnolistener"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrorsLite-UDPLiteDatagramsthatcouldnotbedeliveredtoanapplication"
      },
      {
       "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "RcvbufErrors-UDPbuffererrorsreceived"
      },
      {
       "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SndbufErrors-UDPbuffererrorssend"
      }
     ]
    },
    {
     "title": "TCPIn/Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InSegs-Segmentsreceived,includingthosereceivedinerror.Thiscountincludessegmentsreceivedoncurrentlyestablishedconnections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutSegs-Segmentssent,includingthoseoncurrentconnectionsbutexcludingthosecontainingonlyretransmittedoctets"
      }
     ]
    },
    {
     "title": "TCPErrors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ListenOverflows-Timesthelistenqueueofasocketoverflowed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ListenDrops-SYNstoLISTENsocketsignored"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "TCPSynRetrans-SYN-SYN/ACKretransmitstobreakdownretransmissionsinSYN,fast/timeoutretransmits"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "RetransSegs-Segmentsretransmitted-thatis,thenumberofTCPsegmentstransmittedcontainingoneormorepreviouslytransmittedoctets"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrs-Segmentsreceivedinerror(e.g.,badTCPchecksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutRsts-SegmentssentwithRSTflag"
      }
     ]
    },
    {
     "title": "TCPConnections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "CurrEstab-TCPconnectionsforwhichthecurrentstateiseitherESTABLISHEDorCLOSE-WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "MaxConn-LimitonthetotalnumberofTCPconnectionstheentitycansupport(Dynamicis\"-1\")"
      }
     ]
    },
    {
     "title": "TCPSynCookie",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SyncookiesFailed-InvalidSYNcookiesreceived"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SyncookiesRecv-SYNcookiesreceived"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SyncookiesSent-SYNcookiessent"
      }
     ]
    },
    {
     "title": "TCPDirectTransition",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ActiveOpens-TCPconnectionsthathavemadeadirecttransitiontotheSYN-SENTstatefromtheCLOSEDstate"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "PassiveOpens-TCPconnectionsthathavemadeadirecttransitiontotheSYN-RCVDstatefromtheLISTENstate"
      }
     ]
    },
    {
     "title": "TCPStat",
     "type": "timeseries",
     "description": "Enablewith--collector.tcpstatargumentonnode-exporter",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_tcp_connection_states{state=\"established\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "established-TCPsocketsinestablishedstate"
      },
      {
       "expr": "node_tcp_connection_states{state=\"fin_wait2\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "fin_wait2-TCPsocketsinfin_wait2state"
      },
      {
       "expr": "node_tcp_connection_states{state=\"listen\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "listen-TCPsocketsinlistenstate"
      },
      {
       "expr": "node_tcp_connection_states{state=\"time_wait\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "time_wait-TCPsocketsintime_waitstate"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeExporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NodeExporterScrapeTime",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}}-Scrapeduration"
      }
     ]
    },
    {
     "title": "NodeExporterScrape",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}}-Scrapesuccess"
      },
      {
       "expr": "node_textfile_scrape_error{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}}-Scrapetextfileerror(1=true)"
      }
     ]
    }
   ]
  }
 ]
}