kind: Namespace
apiVersion: v1
metadata:
  name: n8n
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n
        ports:
        - containerPort: 5678
        env:
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          value: "n8n"
        - name: N8N_BASIC_AUTH_PASSWORD
          value: "n8n"
        - name: GENERIC_TIMEZONE
          value: "Asia/Tokyo"
        - name: N8N_METRICS
          value: "true"
        - name: DB_TYPE
          value: "postgresdb"
        - name: DB_POSTGRESDB_HOST
          value: "postgres-service"
        - name: DB_POSTGRESDB_USER
          value: "n8n"
        - name: DB_POSTGRESDB_PASSWORD
          value: "mysecretpassword"

---

apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "5678"
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
  - protocol: TCP
    port: 5678

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  annotations:
    tailscale.com/ingress-class: tailscale
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - n8n
  rules:
  - host: n8n
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 5678 
