global:
  slack_api_url_file: '/etc/alertmanager/slack_url'

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - channel: '#ops'
        title_link: 'http://otknoy-k8s/alertmanager/#/alerts?receiver={{ .Receiver | urlquery }}'
        text: '{{ .CommonAnnotations.summary }}'
        send_resolved: true
