global:
  slack_api_url: 

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
     - channel: '#ops'
       title_link: 'http://localhost:9093/#/alerts?receiver={{ .Receiver | urlquery }}'
       text: '{{ .CommonAnnotations.summary }}'
       send_resolved: true
