groups:

  - name: sample
    rules:
    - alert: NodeInstanceDown
      expr: up{job='node'} == 0
      for: 30s

  - name: room
    rules:
    - alert: low templature
      expr: MultiFunctionLight_temperature <= 18
    - alert: high templature
      expr: MultiFunctionLight_temperature >= 28
    - alert: low humidity
      expr: MultiFunctionLight_humidity <= 45
    - alert: high humidity
      expr: MultiFunctionLight_humidity >= 65
  
