groups:

  - name: sample
    rules:
    - alert: NodeInstanceDown
      expr: up{job='node'} == 0
      for: 30s

  - name: room
    rules:
    - alert: low templature
      expr: MultiFunctionLight_temperature <= 18
      labels:
        severity: warn
      annotations:
        summary: "Low tempature: {{ humanize $value }}℃"
    - alert: high templature
      expr: MultiFunctionLight_temperature >= 28
      labels:
        severity: warn
      annotations:
        summary: "High tempature: {{ humanize $value }}℃"
    - alert: low humidity
      expr: MultiFunctionLight_humidity <= 40
      labels:
        severity: warn
      annotations:
        summary: "Low humidiry: {{ humanize $value }}%"
    - alert: high humidity
      expr: MultiFunctionLight_humidity >= 60
      labels:
        severity: warn
      annotations:
        summary: "High Humidity: {{ humanize $value }}%"

  - name: debian
    rules:
    - alert: disk usage
      expr: |
        100 * (1 - (node_filesystem_free_bytes{job="debian"} / node_filesystem_size_bytes{job="debian"})) >= 85
      labels:
        severity: warn
      annotations:
        summary: "disk usage too high: {{ humanize $value }}%"
    - alert: disk unmounted
      expr: |
        count(node_disk_info{job="debian"}) != 3
      labels:
        severity: warn
      annotations:
        summary: "disk is unmounted"
