global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
          - 'localhost:9090'
  - job_name: 'debian'
    static_configs:
      - targets:
        - '192.168.1.50:9100'
  - job_name: 'mflight-api'
    scrape_interval: 60s
    static_configs:
      - targets:
        - 'mflight-api:5000'
