global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
          - 'localhost:9090'
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets:
          - 'pushgateway:9091'
  - job_name: 'debian'
    static_configs:
      - targets:
        - 'host.docker.internal:9100'
  - job_name: 'proxmox'
    static_configs:
      - targets:
        - 'pve001:9100'
  - job_name: 'roomctl'
    scrape_interval: 60s
    static_configs:
      - targets:
        - 'roomctl:9199'
