global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
          - 'localhost:9090'
  - job_name: 'debian'
    static_configs:
      - targets:
        - '192.168.1.50:9100'
  - job_name: 'mflight-exporter'
    scrape_interval: 60s
    static_configs:
      - targets:
        - 'mflight-exporter:5000'
