apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-url-secret
  namespace: monitoring
spec:
  encryptedData:
    slack_url: AgB348mXYfTZ7xTNSolT6GsqMr0QF7kMTEROQlnNQU7J9bcVBnFp2I7kso8HdPRLuPU1h5u40TNSAWATTHA1wgn5tmFGhtRoPXG1+y0wi0f+BvtEAbgGCjgZorwmGsaF1bAEZzuExxjKA5h8U/7XMlVQyko9sGBkG3DZ417P6NoSKbID+b+n/zmZYq1+LZbvY2FNO9nLotpDDdp9G1g5vANN0KOrn2HXZimmespi1ghGBmwUSB17WwEK51CAZzn1D3BLwnvflSrTgw6OOdnnMdr/LkSCDllhtUC7FwyDrQwGc8mP8rAWuPhTdeJyj/6bR24RLTRzYs5LSk6wEzxKlPVOF00/8g4Raw5/Mp5hLM1Vt68DkVDbL8uLDftlbpVcjGDG0TUEIGOK3rND+RHYVyRji5b0tMSx25GNLWjUlPonZigNJ+M9kqghdxocL6q4TLM/liawN3gZoDh6WEIy5mxAifhEjXfM+o5S18LUrZxUMIx5zgsmWLeTWMi2adsUrFFijBpTBcGFo0WtJyuVij6rvf2ClFZ0qrlISq8ZyG1vQS3Jrve2ALzTFCDeZVSzaArp/3A2e6cAS82JRo3VsXvodELzmqMcxMNEVa3jj/6U+Q2o4x3lTOJHNXD00xldUpKSog97pPT9J+ljqeNK96IIzsgWUnQQ3+8FuPQ5NdzwSzqFquJqIIzstwtKUeywcCHquMwhZ77cN0ny3RL7TM/oJq40uXDNnKRnLXqlYhl0iTDZpRB44deXg3l3bPHTb83527djOTP6VpI3b40iqdMr84FRSOP7BcwN4qz3FGay
  template:
    metadata:
      name: alertmanager-slack-url-secret
      namespace: monitoring
