apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.34.1
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.external-url=http://otknoy-k8s/alertmanager/
            - --web.route-prefix=/
          ports:
            - containerPort: 9093
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager/
      volumes:
        - name: alertmanager-config-volume
          projected:
            sources:
              - configMap:
                  name: alertmanager-cm
              - secret:
                  name: alertmanager-slack-url-secret

---

apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
