apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      group: gateway.envoyproxy.io
      version: v1alpha1
      kind: EnvoyProxy
      name: home-server
    patch: |-
      - op: replace
        path: /spec/provider/kubernetes/envoyService/annotations/metallb.io~1loadBalancerIPs
        value: 192.168.0.128
      - op: add
        path: /spec/provider/kubernetes/envoyService/annotations/tailscale.com~1expose
        value: "true"
      - op: add
        path: /spec/provider/kubernetes/envoyService/annotations/tailscale.com~1hostname
        value: otknoy-k8s
