services:
  grafana:
    image: grafana/grafana-oss:10.0.2
    environment:
      GF_USERS_VIEWERS_CAN_EDIT: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - 3000:3000
    restart: always
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus/data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=2y'
      - '--web.external-url=http://localhost:9090'
    ports:
      - 9090:9090
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./.slack_url:/etc/alertmanager/slack_url:ro
    ports:
      - 9093:9093
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.6.0
    ports:
      - 9091:9091
    restart: always
  # node-exporter:
  #   image: prom/node-exporter:v0.18.1
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   ports:
  #     - 9100:9100

  roomctl:
    image: ghcr.io/otknoy/roomctl:20230615144055
    ports:
      - 9199:9199
    environment:
      APP_PORT: 9199
      APP_SWITCHBOT_TOKEN:      ${APP_SWITCHBOT_TOKEN}
      APP_SWITCHBOT_DEVICEID:   ${APP_SWITCHBOT_DEVICEID}
      APP_SWITCHBOT_DEVICENAME: ${APP_SWITCHBOT_DEVICENAME}
    restart: always
