services:
  grafana:
    image: grafana/grafana:8.5.3
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "hogehoge"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    restart: always
  prometheus:
    image: prom/prometheus:v2.35.0
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus/data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=2y'
      - '--web.external-url=http://localhost:9090'
    ports:
      - 9090:9090
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  alertmanager:
    build: alertmanager
    environment:
      SLACK_API_URL: ${SLACK_API_URL}
    ports:
      - 9093:9093
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.4.1
    ports:
      - 9091:9091
    restart: always
  # node-exporter:
  #   image: prom/node-exporter:v0.18.1
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   ports:
  #     - 9100:9100

  mflight-api:
    image: otknoy/mflight-api:20220319-143030
    ports:
      - 5000:5000
    environment:
      APP_PORT: "5000"
      APP_MFLIGHT_URL: "http://192.168.1.10:56002"
      APP_MFLIGHT_MOBILE_ID: "03050100-0200-8f00-0000-00000019f855"
      APP_MFLIGHT_CACHE_TTL: "15s"
    restart: always
