services:
  # node-exporter:
  #   image: prom/node-exporter:v0.18.1
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   ports:
  #     - 9100:9100

  roomctl:
    image: ghcr.io/otknoy/roomctl:20231108005101
    ports:
      - 9199:9199
    environment:
      APP_PORT: 9199
      APP_SWITCHBOT_TOKEN:      ${APP_SWITCHBOT_TOKEN}
      APP_SWITCHBOT_DEVICEID:   ${APP_SWITCHBOT_DEVICEID}
      APP_SWITCHBOT_DEVICENAME: ${APP_SWITCHBOT_DEVICENAME}
    restart: always
