services:
  grafana:
    image: grafana/grafana:9.2.4
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "hogehoge"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    restart: always
  prometheus:
    image: prom/prometheus:v2.40.1
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus/data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=2y'
      - '--web.external-url=http://localhost:9090'
    ports:
      - 9090:9090
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  alertmanager:
    build: alertmanager
    environment:
      SLACK_API_URL: ${SLACK_API_URL}
    ports:
      - 9093:9093
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.4.3
    ports:
      - 9091:9091
    restart: always
  # node-exporter:
  #   image: prom/node-exporter:v0.18.1
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   ports:
  #     - 9100:9100

  roomctl:
    image: ghcr.io/otknoy/roomctl:20221108131140
    ports:
      - 9199:9199
    environment:
      APP_PORT: 9199
      APP_SWITCHBOT_TOKEN:    ${APP_SWITCHBOT_TOKEN}
      APP_SWITCHBOT_DEVICEID: ${APP_SWITCHBOT_DEVICEID}
      APP_MFLIGHT_URL:        ${APP_MFLIGHT_URL}
      APP_MFLIGHT_MOBILEID:   ${APP_MFLIGHT_MOBILEID}
    restart: always
