version: '2'
services:
  grafana:
    image: grafana/grafana:7.1.0
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    mem_limit: 128m
  prometheus:
    image: prom/prometheus:v2.20.0
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=2y'
    ports:
      - 9090:9090
    mem_limit: 1024m

  # node-exporter:
  #   image: prom/node-exporter:v0.18.1
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   mem_limit: 32m
  #   ports:
  #     - 9100:9100

  mflight-exporter:
    image: mflight-exporter:dev
    mem_limit: 32m
    ports:
      - 5000:5000
