version: '2'
services:
  grafana:
    image: grafana/grafana:6.4.3
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    mem_limit: 128m
  prometheus:
    image: prom/prometheus:v2.12.0
    volumes:
      - ./prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    mem_limit: 1024m
  influxdb:
    image: influxdb:1.7.8
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: prometheus
    ports:
      - 8086:8086
    mem_limit: 1048m

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    mem_limit: 32m
    ports:
      - 9100:9100
