version: '2'
services:
  grafana:
    image: grafana/grafana:6.1.4
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    mem_limit: 128m
  prometheus:
    image: prom/prometheus:v2.8.1
    volumes:
      - ./prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    mem_limit: 512m
  influxdb:
    image: influxdb:1.7.5
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: prometheus
    ports:
      - 8086:8086
    mem_limit: 512m

  node-exporter:
    image: quay.io/prometheus/node-exporter
    ports:
      - 9100:9100
    volumes:
      # - /proc:/host/proc
      # - /sys:/host/sys
      - /:/host:ro,rslave
      - /:/rootfs:ro
    mem_limit: 128m
