{
 "title": "localhost",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "job", "query": "debian" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"},instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "My Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roomctl_temperature{device_name!=\"\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "roomctl_temperature", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "roomctl_humidity", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roomctl_humidity{device_name!=\"\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 } },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk usage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance, device) (1 - (node_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\"} / node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\"}))",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device!~\"(br|veth).+\"}[$__rate_interval]))",
     "legendFormat": "transmit: {{instance}} {{device}}"
    },
    {
     "expr": "- sum by (instance, device) (rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device!~\"(br|veth).+\"}[$__rate_interval]))",
     "legendFormat": "receive: {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "node: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (mode) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"$instance\"}[1m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Disk usage rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (mountpoint) (1 - (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\", device=~\"/.*\"} / node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$instance\", device=~\"/.*\"}))",
       "legendFormat": "{{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "thermal sensor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg_over_time(node_hwmon_temp_celsius{job=\"node-exporter\", instance=\"$instance\"}[2m]) > 0",
       "legendFormat": "{{chip}}: {{sensor}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"$instance\"}[1m])",
       "legendFormat": "read: {{device}}"
      },
      {
       "expr": "-irate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"$instance\"}[1m])",
       "legendFormat": "write: {{device}}"
      }
     ]
    },
    {
     "title": "CPU freq",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "node_cpu_scaling_frequency_hertz{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "fan rpm",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "node_hwmon_fan_rpm{job=\"node-exporter\", instance=\"$instance\"} > 0",
       "legendFormat": "{{chip}} {{sensor}}"
      }
     ]
    },
    {
     "title": "Disk used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$instance\", device=~\"/.*\"} - node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\", device=~\"/.*\"})\n",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "transmit"
      },
      {
       "expr": "- sum(rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "receive"
      }
     ]
    },
    {
     "title": "Disk usage rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (mountpoint) (1 - (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\", device=~\"/.*\"} / node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$instance\", device=~\"/.*\"}))",
       "legendFormat": "{{device}} {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "temp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus TSDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_storage_blocks_bytes",
       "legendFormat": "used"
      }
     ]
    }
   ]
  }
 ]
}