{
 "title": "localhost",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "job", "query": "debian" },
   { "name": "instance", "query": "host.docker.internal:9100" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "My Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roomctl_temperature{device_name!=\"\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "roomctl_temperature", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "roomctl_humidity", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roomctl_humidity{device_name!=\"\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  { "title": "PC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (device, mountpoint) (1 - (node_filesystem_avail_bytes{job=\"$job\", instance=~\"$instance\", device=~\"/.*\"} / node_filesystem_size_bytes{job=\"$job\", instance=~\"$instance\", device=~\"/.*\"}))",
     "legendFormat": "{{device}} {{mountpoint}}"
    }
   ]
  },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{job=\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\", instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (device, mountpoint) (node_filesystem_size_bytes{job=\"$job\", instance=~\"$instance\", device=~\"/.*\"} - node_filesystem_avail_bytes{job=\"$job\", instance=~\"$instance\", device=~\"/.*\"})\n",
     "legendFormat": "{{device}} {{mountpoint}}"
    }
   ]
  },
  { "title": "PC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "thermal sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{job=\"$job\", instance=~\"$instance\"}[2m]) > 0",
     "legendFormat": "{{chip}}: {{sensor}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read: {{device}}"
    },
    {
     "expr": "-irate(node_disk_written_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "write: {{device}}"
    }
   ]
  },
  {
   "title": "CPU freq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk usage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (mountpoint) (1 - (node_filesystem_avail_bytes{job=\"$job\", instance=~\"$instance\", device=~\"/.*\"} / node_filesystem_size_bytes{job=\"$job\", instance=~\"$instance\", device=~\"/.*\"}))",
     "legendFormat": "{{device}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read: {{device}}"
    },
    {
     "expr": "-irate(node_disk_write_time_seconds_total{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "write: {{device}}"
    }
   ]
  },
  {
   "title": "fan rpm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{job=\"$job\"} > 0",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "- sum(rate(node_network_receive_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_weighted_seconds_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "proxmox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"proxmox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"proxmox\"} - node_memory_MemAvailable_bytes{job=\"proxmox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_size_bytes{job=\"proxmox\", device=~\"/.*\"} - node_filesystem_avail_bytes{job=\"proxmox\", device=~\"/.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "k8s nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"k8s-nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"k8s-nodes\"} - node_memory_MemAvailable_bytes{job=\"k8s-nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_size_bytes{job=\"k8s-nodes\", device=~\"/.*\"} - node_filesystem_avail_bytes{job=\"k8s-nodes\", device=~\"/.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus TSDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_storage_blocks_bytes",
       "legendFormat": "used"
      }
     ]
    }
   ]
  }
 ]
}