namespace: kube-system

resources:
- ./kube-state-metrics/cluster-role.yaml
- ./kube-state-metrics/deployment.yaml
- ./kube-state-metrics/service-account.yaml
- ./kube-state-metrics/service.yaml
- ./metrics-server/components.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
    target:
      version: v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
