{
 "title": "k8s",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "kube_node_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (os_image, kubelet_version) (kube_node_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "k8s node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "node_load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_load1{job=\"kubernetes-node-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"kubernetes-node-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"kubernetes-node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"kubernetes-node-exporter\"} - node_memory_MemAvailable_bytes{job=\"kubernetes-node-exporter\"}) / node_memory_MemTotal_bytes{job=\"kubernetes-node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{job=\"kubernetes-node-exporter\", mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (device) (rate(node_network_transmit_bytes_total{job=\"kubernetes-node-exporter\"}[$__rate_interval]))",
     "legendFormat": "transmit: {{device}}"
    },
    {
     "expr": "- sum by (device) (rate(node_network_receive_bytes_total{job=\"kubernetes-node-exporter\"}[$__rate_interval]))",
     "legendFormat": "receive: {{device}}"
    }
   ]
  },
  {
   "title": "CPU freq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{job=\"kubernetes-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "cpu package throttles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(node_cpu_package_throttles_total[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "thermal sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{job=\"kubernetes-node-exporter\"}[2m])",
     "legendFormat": "{{chip}}: {{sensor}}"
    }
   ]
  },
  { "title": "k8s pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".+\"}[5m]))\n",
     "legendFormat": "{{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (container_memory_usage_bytes{namespace=~\"$namespace\", container=~\".+\"})\n",
     "legendFormat": "{{namespace}} {{pod}}"
    }
   ]
  }
 ]
}