{
 "title": "Synology NAS Details",
 "description": "The Synology NAS Details dashboard provides detailed information as to the operational status of the system(s).",
 "tags": [
  "synology",
  "dsm"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "NASDevices", "query": "4" },
   { "name": "interfacebits", "query": "8" },
   { "name": "JobName", "label": "Job Name", "query": { "query": "label_values(ssCpuUser, job)" } },
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$JobName'})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "InterfacePhysical",
    "label": "Network Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "InterfaceVirtual",
    "label": "Virtual Interfaces",
    "query": {
     "query": "label_values(ifType_info{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "DiskName",
    "label": "Disk",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "DiskNameSSD",
    "label": "Cache",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "raidName",
    "label": "Storage",
    "query": {
     "query": "label_values(raidName{job=~'$JobName',instance=~'$Device'},raidName)"
    }
   },
   {
    "name": "storageIODevice",
    "label": "Disk",
    "query": {
     "query": "label_values(storageIODevice{job=~'$JobName',instance=~'$Device'},storageIODevice)"
    }
   },
   {
    "name": "spaceIODevice",
    "label": "Volume Name",
    "query": {
     "query": "label_values(spaceIODevice{job=~'$JobName',instance=~'$Device'},spaceIODevice)"
    }
   },
   {
    "name": "hrStorageDescr",
    "label": "File System",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "flashCacheDisk",
    "label": "Cache",
    "query": {
     "query": "label_values(flashCacheSSDDev{job=~'$JobName',instance=~'$Device'},flashCacheSSDDev)"
    }
   },
   {
    "name": "hrMemoryDescr",
    "label": "Memory",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "SmartDev",
    "label": "S.M.A.R.T",
    "query": {
     "query": "label_values(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device'},diskSMARTInfoDevName)"
    }
   },
   {
    "name": "services",
    "query": {
     "query": "label_values(serviceName{job=~'$JobName',instance=~'$Device'},serviceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System State - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Information - $Device",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sysUpTime{job=~'$JobName',instance=~'$Device'}/100",
     "legendFormat": "uptime"
    },
    {
     "expr": "upgradeAvailable{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "(temperature{job=~'$JobName',instance=~'$Device'}*9/5)+32"
    },
    {
     "expr": "cpuFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "powerStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "modelName{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "version{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "serialNumber{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}+1"
    }
   ]
  },
  {
   "title": "Synology Systems",
   "type": "stat",
   "description": "Enter the number of Synology's you are monitoring in the NASDevices variable. A positive Number here means there is a NAS down or not being scraped for data. A negative Number means you are collecting data from more Synology's than the system expects in the NASDevices variable.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(systemStatus)", "legendFormat": "Total Synology's" },
    {
     "expr": "$NASDevices-count(systemStatus)",
     "legendFormat": "Synology's Down"
    }
   ]
  },
  {
   "title": "Network Interface Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2)",
     "legendFormat": "Admin Down"
    },
    {
     "expr": "(count(ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2)) - (count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2))",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Storage Volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})",
     "legendFormat": "Total Storage"
    },
    {
     "expr": "count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=2 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=10) or (raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=13 and {job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=20))",
     "legendFormat": "RAID Warning"
    },
    {
     "expr": "count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=11 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=12) or raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>21)",
     "legendFormat": "RAID Failure"
    }
   ]
  },
  {
   "title": "Hard Drives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'})",
     "legendFormat": "Total Drives"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=2) and count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}<=3)",
     "legendFormat": "Not Used"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=4)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Cache Drives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'})",
     "legendFormat": "Total Drives"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}==3)",
     "legendFormat": "Not Used"
    },
    {
     "expr": "count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskNameSSD'}>=4)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "S.M.A.R.T Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}==1)",
     "legendFormat": "SMART Checks"
    },
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}==1)",
     "legendFormat": "SMART Failures"
    }
   ]
  },
  {
   "title": "System Resources - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Used"
      },
      {
       "expr": "100-(ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'})",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Usage - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Used"
      },
      {
       "expr": "1-((memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "CPU Utilization - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "System"
      },
      {
       "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "User"
      },
      {
       "expr": "ssCpuIdle{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Physical Memory - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} ",
       "legendFormat": "Size"
      },
      {
       "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} - (memShared{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'} + memAvailReal{job=~'$JobName',instance=~'$Device'})",
       "legendFormat": "Reserved"
      },
      {
       "expr": "memBuffer{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "memCached{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Cached"
      },
      {
       "expr": "memShared{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Shared"
      },
      {
       "expr": "memAvailReal{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "CPU Load - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "laLoadInt{job=~'$JobName',instance=~'$Device'}/100",
       "legendFormat": "{{laNames}}"
      }
     ]
    },
    {
     "title": "Virtual Memory - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Size"
      },
      {
       "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}) - memTotalFree{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Used"
      },
      {
       "expr": "memTotalFree{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Processes - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hrSystemProcesses{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Users / Service - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "serviceUsers{job=~'$JobName',instance=~'$Device',serviceName=~'$services'}",
       "legendFormat": "{{serviceName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Internals - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Interfaces - ($Device)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      }
     ]
    },
    {
     "title": "Hard Drives  - ($Device)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(diskTemperature{job=~'$JobName',instance=~'$Device'}*9/5)+32"
      },
      {
       "expr": "diskType{job=~'$JobName',instance=~'$Device'}"
      },
      {
       "expr": "diskStatus{job=~'$JobName',instance=~'$Device'}"
      },
      {
       "expr": "diskModel{job=~'$JobName',instance=~'$Device'}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage: $raidName - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "raidName",
   "targets": [
    {}
   ]
  },
  {
   "title": "RAID Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
    }
   ]
  },
  {
   "title": "Storage Usage - $raidName ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}-raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'})",
     "legendFormat": "Used"
    },
    {
     "expr": "raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
    }
   ]
  },
  {
   "title": "% Used Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}-raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})/raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})*100",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "HDD/SSD: $storageIODevice - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "storageIODevice",
   "targets": [
    {}
   ]
  },
  {
   "title": "Bits Read/Write: $storageIODevice - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(storageIONReadX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "Read Bits"
    },
    {
     "expr": "rate(storageIONWrittenX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "Write Bits"
    }
   ]
  },
  {
   "title": "I/O: $storageIODevice - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(storageIOLA{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "I/0"
    },
    {
     "expr": "rate(storageIOLA1{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "I/O 1 min avg"
    },
    {
     "expr": "rate(storageIOLA5{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "I/O 5 min avg"
    },
    {
     "expr": "rate(storageIOLA15{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "I/O 15  min avg"
    }
   ]
  },
  {
   "title": "Load: $storageIODevice - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(storageIOReads{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "Read Load"
    },
    {
     "expr": "irate(storageIOWrites{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
     "legendFormat": "Write Load"
    }
   ]
  },
  {
   "title": "Volume: $spaceIODevice - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "repeat": "spaceIODevice",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume Throughput - $spaceIODevice ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(spaceIONReadX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIONWrittenX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Volume IOPS - $spaceIODevice ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(spaceIOReads{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIOWrites{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "SMART - ($SmartDev)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "repeat": "SmartDev",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "S.M.A.R.T ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName=~'$SmartDev'})",
       "legendFormat": "SMART Checks"
      }
     ]
    },
    {
     "title": "S.M.A.R.T: $SmartDev (Data is from the last time the Scheduled task was run)",
     "type": "table",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 48 },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName='$SmartDev'}",
       "legendFormat": "SMARTInfo"
      },
      {
       "expr": "diskSMARTAttrName{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrCurrent{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrCurrent"
      },
      {
       "expr": "diskSMARTAttrThreshold{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrThreshold"
      },
      {
       "expr": "diskSMARTAttrWorst{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrWorst"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrStatus"
      },
      {
       "expr": "diskSMARTAttrRaw{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrRaw"
      }
     ]
    },
    {
     "title": "S.M.A.R.T: $SmartDev",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName=~'$SmartDev'}",
       "legendFormat": "diskSMARTInfoDevName"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}",
       "legendFormat": "diskSMARTAttrStatus"
      }
     ]
    }
   ]
  }
 ]
}