version: '2'
services:

  rproxy:
    image: nginx:1.20.0-alpine
    depends_on:
      - web-server
      - webdav
      # - jupyter-notebook
      # - solr
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    mem_limit: 16m

  web-server:
    image: nginx:1.20.0-alpine
    ports:
      - 10080:80
    volumes:
      - ./public_html/:/usr/share/nginx/html:ro
    mem_limit: 16m

  # jupyter-notebook:
  #   image: jupyter/datascience-notebook
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - /home/otknoy/notebook:/home/jovyan/work
  #   command: start-notebook.sh --NotebookApp.password='sha1:76217d692f67:d46b306c90936cb8e3f0532db389749cb3650c10' --NotebookApp.base_url='/notebook'
  #   environment:
  #     TZ: 'Asia/Tokyo'
  #   mem_limit: 8g

  # solr:
  #   image: solr:7.5
  #   ports:
  #     - 8983:8983
  #   volumes:
  #     - ./solr_core:/opt/solr/server/solr/mycores

  samba:
    build: samba
    environment:
      USER: otknoy
      PASSWORD: passon
    ports:
      - 139:139
      - 445:445
    volumes:
      - /home/otknoy:/mnt/share/home/otknoy
      - /mnt/backup:/mnt/share/backup
      - /mnt/private:/mnt/private
    mem_limit: 32m

  webdav:
    build: wsgidav
    ports:
      - 8081:8080
    environment:
      USER: ${WEBDAV_USER}
      PASSWORD: ${WEBDAV_PASSWORD}
    volumes:
      - /mnt/private/:/var/wsgidav-root:ro
