apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: debian
            - name: NFS_PATH
              value: /
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: nfs-client-root
          nfs:
            server: debian
            path: /
