services:

  # jupyter-notebook:
  #   image: jupyter/datascience-notebook
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - /home/otknoy/notebook:/home/jovyan/work
  #   command: start-notebook.sh --NotebookApp.password='sha1:76217d692f67:d46b306c90936cb8e3f0532db389749cb3650c10' --NotebookApp.base_url='/notebook'
  #   environment:
  #     TZ: 'Asia/Tokyo'

  # solr:
  #   image: solr:7.7.3
  #   ports:
  #     - 8983:8983
  #   volumes:
  #     - ./solr_core:/opt/solr/server/solr/mycores

  samba:
    build: ../docker/samba
    environment:
      USER: ${SAMBA_USER}
      PASSWORD: ${SAMBA_PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
      - /home/otknoy:/mnt/share/home/otknoy:ro
      - /mnt/temp:/mnt/temp
      - /mnt/private:/mnt/private
    restart: always
