apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: app
spec:
  encryptedData:
    .dockerconfigjson: AgCYtCTgjQLAZJNN2H9Rlu0rAh415d7FTjqUhIBwehjot/n91GmZskBWi4o/N2chyjdo7ytNv/+aoFuICAlfz1GjHbKfCEYzk12cHIva16dACKfaSQw0WCQOYEEqGg/HS5H8RnFdcli4Ntj5adMFFdiXemuXxMJDyBWd8q4ZZnigcWcmqVxCZy2MmMLoUaMMd5ucufrOXOnA6MLwLZM0pEqN4vTVBTpU7GJL1MltJIrBZINUv0mRHwzpZxRyr0j6gJjqjcijRKVtEX6tDszMwGNgi5BLeq5fzL/WsH/wuK1riOkawU6AtpNxvcjqsyJ3gJ/f/HDNiD78iT9ickfriWE2kV5uwVF/WQZCox46oJY8ywkECY8u8j717hIZuMuhOFFP2Ioo8ZyO5p2y/kJQw9lfPLIr1FbI6XQxhQzt3soMm486gyes+q6SbGX77LJ6G/B5v2RhYlrJNCMFwvOcgqffqRTzxRD9RHtF84zEPwd6xKDqM3BoivB92zc2JgxrJ0RdYf4ObOVBLB3qOeixkMNJ6bvR7mvc+ZCB9i+ySzuOsW0V2lVf3SvEsH16ZlNY+kc8qeSTUWHC+tO51t4pp3mA6rjko4YLNbN2A9zPvfnJlMlV5Yq+GqrgUW8/s5+UtVMNXE5zCFIZe6bpQt7tMyXkncU2Wh0MacJ6dFxL/+H1wAMRkalrH/BMc1GA2mI+hemv2qAyw2Aap8lQTdThstkx4rtczywFQEqRUUxtksJOJwVn5s82RAHlOPYZRKobdOWJMIkkDWQncWwA1oVt5KVa/OLKICqo7EGfs59R2F9HvAlovrRg31iqKQ3j0ZvbW3/M54Wx
  template:
    metadata:
      name: ghcr-pull
      namespace: app
    type: kubernetes.io/dockerconfigjson
