machine:
  install:
    disk: /dev/nvme0n1
cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          exemptions:
            namespaces:
              - tailscale
  allowSchedulingOnControlPlanes: true
