apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- deployment.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/version: 2.15.0

images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.16.0
