version: '3'
services:

  samba:
    build: ../docker/samba
    environment:
      USER: ${SAMBA_USER}
      PASSWORD: ${SAMBA_PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
      - /home/otknoy:/mnt/share/home/otknoy:ro
      - /mnt/backup:/mnt/backup
    restart: always
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    privileged: true
    ports:
      - "2049:2049"
    environment:
      SHARED_DIRECTORY: /export
    volumes:
      - ./nfs-server/data:/export

  prometheus:
    image: prom/prometheus:v2.49.1
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus/data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=2y'
      - '--web.external-url=http://localhost:9090'
    ports:
      - 9090:9090
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always

  roomctl:
    image: ghcr.io/otknoy/roomctl:20240211011139
    ports:
      - 9199:9199
    environment:
      APP_PORT: 9199
      APP_SWITCHBOT_TOKEN:      ${APP_SWITCHBOT_TOKEN}
      APP_SWITCHBOT_DEVICEID:   ${APP_SWITCHBOT_DEVICEID}
      APP_SWITCHBOT_DEVICENAME: ${APP_SWITCHBOT_DEVICENAME}
    restart: always

