version: '3'
services:

  reverse-proxy:
    image: nginx:1.25.3-alpine
    depends_on:
      - web-server
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 81:80
    restart: always

  web-server:
    image: nginx:1.25.3-alpine
    ports:
      - 10080:80
    volumes:
      - ./web-server/public_html/:/usr/share/nginx/html:ro
    restart: always

  samba:
    build: ../docker/samba
    environment:
      USER: ${SAMBA_USER}
      PASSWORD: ${SAMBA_PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
      - /home/otknoy:/mnt/share/home/otknoy:ro
      - /mnt/backup:/mnt/backup
    restart: always
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    privileged: true
    ports:
      - "2049:2049"
    environment:
      SHARED_DIRECTORY: /export
    volumes:
      - ./nfs-server/data:/export

  grafana:
    image: grafana/grafana-oss:10.3.3
    environment:
      GF_USERS_VIEWERS_CAN_EDIT: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - 3000:3000
    restart: always

  prometheus:
    image: prom/prometheus:v2.49.1
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus/data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=2y'
      - '--web.external-url=http://localhost:9090'
    ports:
      - 9090:9090
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.26.0
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./.slack_url:/etc/alertmanager/slack_url:ro
    ports:
      - 9093:9093
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.7.0
    ports:
      - 9091:9091
    restart: always

  roomctl:
    image: ghcr.io/otknoy/roomctl:20240211011139
    ports:
      - 9199:9199
    environment:
      APP_PORT: 9199
      APP_SWITCHBOT_TOKEN:      ${APP_SWITCHBOT_TOKEN}
      APP_SWITCHBOT_DEVICEID:   ${APP_SWITCHBOT_DEVICEID}
      APP_SWITCHBOT_DEVICENAME: ${APP_SWITCHBOT_DEVICENAME}
    restart: always

