version: '3'
services:

  samba:
    build: ../docker/samba
    environment:
      USER: ${SAMBA_USER}
      PASSWORD: ${SAMBA_PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
      - /home/otknoy:/mnt/share/home/otknoy:ro
      - /mnt/backup:/mnt/backup
    restart: always
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    privileged: true
    ports:
      - "2049:2049"
    environment:
      SHARED_DIRECTORY: /export
    volumes:
      - ./nfs-server/data:/export

