apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-retain
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  onDelete: retain
