global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
          - 'localhost:9090'
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'

remote_write:
- url: http://influxdb:8086/api/v1/prom/write?db=prometheus
  queue_config:
    capacity: 1000000
    batch_send_deadline: 10s
    max_samples_per_send: 1000
    max_shards: 3

remote_read:
- url: http://influxdb:8086/api/v1/prom/read?db=prometheus

