global:
  slack_api_url_file: '/etc/alertmanager/slack_url'

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
     - channel: '#ops'
       title_link: 'http://debian-server001:9093/#/alerts?receiver={{ .Receiver | urlquery }}'
       text: '{{ .CommonAnnotations.summary }}'
       send_resolved: true
