apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/cloud/deploy.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Service      
      metadata:
        namespace: ingress-nginx
        name: ingress-nginx-controller
        annotations:
          tailscale.com/expose: true
          tailscale.com/hostname: otknoy-k8s
