apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./upstream/operator.yaml
  - ./secrets
  - ./api-server-proxy-rbac.yaml
  - ./admin-rolebinding.yaml

patches:
  - path: ./remove-operator-oauth-secret.yaml
  - path: ./api-server-proxy-patch.yaml
