all:
  hosts:
    ubuntu-server001:
      ansible_host: ubuntu-server001
    ubuntu-server002:
      ansible_host: ubuntu-server002
    ubuntu-server003:
      ansible_host: ubuntu-server003
  # vars:
  #   override_system_hostname: false

  children:
    kube_control_plane:
      hosts:
        ubuntu-server001:
    kube_node:
      hosts:
        ubuntu-server002:
        ubuntu-server003:
    etcd:
      hosts:
        ubuntu-server001:
    calico_rr:
      hosts: {}

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        calico_rr:
